jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches: fedora-rawhide
- job: copr_build
  metadata:
    targets:
    - fedora-all-x86_64
    - epel-9-x86_64
  trigger: pull_request
- job: tests
  metadata:
    targets:
    - fedora-all-x86_64
  trigger: pull_request
actions:
  get-current-version:
  - python3 setup.py --version
synced_files:
- .packit.yaml
downstream_package_name: openscap-report
upstream_package_name: openscap-report
specfile_path: openscap-report.spec
