jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all-x86_64
    - epel-9-x86_64
  trigger: pull_request
- job: tests
  metadata:
    targets:
    - fedora-all-x86_64
  trigger: pull_request
actions:
  get-current-version:
  - python3 -c "import oscap_report; print(oscap_report.__version__)"
synced_files:
- .packit.yaml
downstream_package_name: openscap-report
upstream_package_name: openscap-report
specfile_path: openscap-report.spec
